# For Linux or any machines with gcc compiler
CC = gcc
CFLAGS = -std=c99 -Wall -pedantic

# For SunOS
#CFLAGS = -Aa

all: mysol

clean:
	/bin/rm *.o mysol

OBJ = tiff.o allocate.o randlib.o

Example: mysol.o $(OBJ) 
	$(CC) $(CFLAGS) -o mysol mysol.o $(OBJ) -lm

